services:
  backend:
    build: ./backend
    image: secure-auth-app-backend
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - backend_data:/app/data
    networks:
      - appnet

  frontend:
    build: ./frontend
    image: secure-auth-app-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - appnet

volumes:
  backend_data:

networks:
  appnet:
    driver: bridge