sonar.projectKey=Secure-web-with-user-authentication
sonar.projectName=Secure web with user authentication
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend

sonar.tests=backend/tests,frontend/tests
sonar.test.inclusions=**/*.test.js,**/*.spec.js

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.host.url=${env.SONAR_HOST_URL}
sonar.token=${env.SONAR_TOKEN}


sonar.cpd.exclusions=**/tests/**,**/*.test.js,**/*.spec.js

sonar.coverage.exclusions=**/tests/**,**/*.test.js,**/*.spec.js