sonar.projectKey=Secure-web-with-user-authentication
sonar.projectName=Secure web with user authentication
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.host.url=http://localhost:9000
sonar.login=sqp_b333e9a9b2911ab72e537158043903c0bfcf5737
