name: SAST Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sast:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm install

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Run all tests with coverage
        run: npm test

      - name: Create backend .env file
        shell: powershell
        run: |
          @"
          SESSION_SECRET=${{ secrets.SESSION_SECRET }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          REDIS_URL=redis://redis:6379
          NODE_ENV=test
          "@ | Out-File -FilePath backend/.env -Encoding utf8

      - name: Build Docker images and start compose
        run: docker-compose up -d --build

      - name: Wait for application startup
        shell: powershell
        run: Start-Sleep -Seconds 45

      - name: OWASP ZAP Baseline Scan
        continue-on-error: true
        shell: powershell
        run: |
          docker run --rm `
            -t ghcr.io/zaproxy/zaproxy:stable `
            zap-baseline.py `
            -t http://host.docker.internal:8080

      - name: Snyk Scan
      # run: npx snyk test --severity-threshold=high
        run: npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk results to dashboard
        run: npx snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Trivy Scan Backend Image
      # run: trivy image --severity HIGH,CRITICAL --exit-code 1 secure-auth-app-backend
        run: trivy image secure-auth-app-backend

      - name: Trivy Scan Frontend Image
      # run: trivy image --severity HIGH,CRITICAL --exit-code 1 secure-auth-app-frontend
        run: trivy image secure-auth-app-frontend

      - name: Generate CycloneDX
        run: npx @cyclonedx/cyclonedx-npm --output-file sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx-sbom
          path: sbom.json

      - name: SonarQube Scan
        shell: powershell
        run: |
          npx sonar-scanner "-Dsonar.projectKey=Secure-web-with-user-authentication" "-Dsonar.sources=backend,frontend" "-Dsonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,backend/coverage/**,frontend/coverage/**" "-Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info" "-Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}" "-Dsonar.login=${{ secrets.SONAR_TOKEN }}"

      - name: Stop containers
        if: always()
        run: docker compose down